version: '3.8'

services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ENABLE_V2=true
    ports:
      - 2379:2379
    networks:
      - pg_network

  patroni1:
    build: .
    container_name: patroni1
    environment:
      - NODE_NAME=patroni1
    volumes:
      - ./pg_data1:/var/lib/postgresql/data
    user: postgres:postgres
    ports:
      - "5532:5432"
      - "8008:8008"
    networks:
      - pg_network
    depends_on:
      - etcd

  patroni2:
    build: .
    container_name: patroni2
    environment:
      - NODE_NAME=patroni2
    volumes:
      - ./pg_data2:/var/lib/postgresql/data
    user: postgres:postgres
    ports:
      - "5533:5432"
      - "8009:8008"
    networks:
      - pg_network
    depends_on:
      - etcd

  patroni3:
    build: .
    container_name: patroni3
    environment:
      - NODE_NAME=patroni3
    volumes:
      - ./pg_data3:/var/lib/postgresql/data
    user: postgres:postgres
    ports:
      - "5534:5432"
      - "8010:8008"
    networks:
      - pg_network
    depends_on:
      - etcd

networks:
  pg_network:
    driver: bridge